// Crossref - Pascal Cross reference
// Version 0.01
// January 9, 2021
// Copyright 2021 Paul Robinson
// Licensed under GPL v2

// Scan.pas - Scan unit

// CrossrefPrefixCode.inc - // STD definitions to be applicable to all files
{$DEFINE BITS64}    { This is compiled for 64-bit machines}
{$UNDEF BITS32}     // Switch these defs for 32-bit compiler
{$UNDEF AUTOVersion}
{$DEFINE Testing}
{$DEFINE Console}

