TYPE
   Work_String         = STRING [ 255 ] ;
   String_80           = STRING [  80 ] ;
   File_Str            = STRING [  64 ] ;
   String_40           = STRING [  40 ] ;
   Name_Str            = STRING [  32 ] ;
   String_25           = STRING [  25 ] ;
   Paragraph           = STRING [  16 ] ;
   String_10           = STRING [  10 ] ;
   String_08           = STRING [   8 ] ;
   Six_Byte            = STRING [   6 ] ;
   Four_Byte           = STRING [   4 ] ;
   String_03           = STRING [   3 ] ;
   Two_Byte            = STRING [   2 ] ;
